# Generated by Django 4.0.3 on 2022-03-22 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, unique=True)),
                ('company_reg_number', models.CharField(max_length=100, unique=True)),
                ('company_address', models.CharField(max_length=100)),
                ('location', models.CharField(choices=[('cbd', 'CBD'), ('graniteside', 'granitiside'), ('willovale', 'willovale'), ('workington', 'workington'), ('borrowdale', 'borrowdale')], default='cbd', max_length=20)),
                ('company_type', models.CharField(choices=[('pbc', 'Public Business Corperation '), ('pvt', 'Private limited')], default='pbc', max_length=50)),
                ('firstname_director', models.CharField(max_length=50)),
                ('firstsurname_director', models.CharField(max_length=50)),
                ('secondname_director', models.CharField(max_length=50)),
                ('secondsurname_director', models.CharField(max_length=50)),
                ('regdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved', models.CharField(default='No Approved', max_length=20)),
                ('companyid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(default='default.jpg', upload_to='product_pics')),
                ('product_name', models.CharField(max_length=50)),
                ('product_price', models.IntegerField()),
                ('product_info', models.CharField(max_length=200)),
                ('product_quantity', models.IntegerField()),
                ('product_category', models.CharField(choices=[('kitchenware', 'kitchenware'), ('clothes', 'clothes'), ('accesories', 'accesories'), ('service', 'service'), ('bevarages', 'bevarages'), ('gadgets', 'gadgets'), ('food', 'food'), ('vehicles', 'vehicles')], default='food', max_length=20)),
                ('dateposted', models.DateTimeField(default=django.utils.timezone.now)),
                ('companyid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('postedbyuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='customer_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productid', models.CharField(max_length=10)),
                ('productname', models.CharField(max_length=100)),
                ('productprice', models.CharField(max_length=100)),
                ('companyname', models.CharField(max_length=100)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
