# Generated by Django 4.0.3 on 2022-03-26 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_customer_order_totalprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_order',
            name='productqty',
            field=models.CharField(default='', max_length=100),
        ),
    ]
